### ISSUE TITLE
Atom Text Editor toolbar text invisible

### ISSUE THREAD

**Issue by Nxt3** [xyl0n/iris#76]
No clue why this became an issue. I applied your most recent commit, and then noticed this. Even after reverting it, the issue is still present. I have a much older version of Iris Light that I applied, and it's fine.

![screenshot from 2014-10-03 21 25 20](https://cloud.githubusercontent.com/assets/2940826/4514321/b561615a-4b65-11e4-97bb-4100f0a98fb9.png)
![screenshot from 2014-10-03 21 25 15](https://cloud.githubusercontent.com/assets/2940826/4514322/b7675df6-4b65-11e4-974a-e7797558c204.png)

**Comment by nathanielw** [comment]
@Nxt3 Did you ever find a solution to this without going back to an old version? I'm still getting light menubars in Atom with the freshest version of Iris.

**Comment by Nxt3** [comment]
I did. I had been making lots of custom changes to Iris, and something I did broke it.

**Comment by nathanielw** [comment]
Hmm, I'm definitely still getting the problem. I think I've found the solution, so I'll open a PR.
